config/routes.rb
Rails.application.routes.draw do
  get 'calculator/show'

  resources :creditors do
    resources :payments
  end
  root :to => 'static#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creditor.rb
class Creditor < ApplicationRecord
  has_many :payments, dependent: :nullify
	[:sum, :months, :rate, :period, :delay_rate].each do |field|
    validates_numericality_of field, on: :create, greater_than: 0
  end
  attr_accessor :delay_from, :total_paid, :must_be_payed, :last_payment
  DEFAULT_RATE = self.column_defaults['rate']
  DEFAULT_DELAY_RATE = self.column_defaults['delay_rate']

  # выручка от вложения
  def self.receipts(sum, rate)
    (rate * 0.01 * sum.to_i).round(2)
  end

  # средняя прибыльность
  def self.rate_of_return
    list = self.all
    list.reduce(0) do |total, element|
      total + element.rate_of_return
    end / list.size
  end

  # прибыльность
  def rate_of_return
    self.last_payment = self.payments.last
    return (self.created_at + self.period.month < Time.now) ? DEFAULT_DELAY_RATE : DEFAULT_RATE unless self.last_payment
    self.determine_delinquencies!
    if self.delay_from
      ontime_months = self.delay_from - 1
      other_months = self.months - ontime_months
      ((ontime_months * DEFAULT_RATE + other_months * DEFAULT_DELAY_RATE) / self.months).round(2)
    else
      DEFAULT_RATE
    end
  end

  # определить наличие посрочек
  def determine_delinquencies!
    n = 0
    loop do
      n += self.period
      nth_payment_time = self.created_at + n.month
      break if nth_payment_time > Time.now
      self.total_paid = self.fact_payment_until(nth_payment_time)
      break if self.total_paid - self.sum > n * self.periodical_commission
      self.must_be_payed += (self.periodical_payment + self.periodical_commission)
      self.check_delay!(n)
    end
  end

  # проверить просрочен ли хоть один платёж
  def check_delay!(n)
    return if self.delay_from
    return if self.total_paid >= self.must_be_payed
    self.delay_from = n
  end

  # оплачено по задолжности
  def total_paid
    @total_paid || 0
  end

  # должно быть оплачено
  def must_be_payed
    @must_be_payed || 0
  end

  # актуальная процентная ставка
  def actual_rate
    (self.delay_from ? DEFAULT_DELAY_RATE : DEFAULT_RATE) / 100
  end

  # сколько фактически оплачено до переданной даты
  def fact_payment_until(payment_time = Time.now)
    self.payments.where("created_at <= '#{payment_time}'").reduce(0) do |total, payment|
      total + payment.amount
    end
  end

  # периодическая выплата
  def periodical_payment
    self.period.to_f / self.months * self.sum
  end

  # периодическая комиссия
  def periodical_commission
    self.sum * self.actual_rate * self.period / 12.0
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :creditor
  validates_numericality_of :amount, on: :create, greater_than: 0
  CURRENCY = '₽'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/creditors_controller.rb
class CreditorsController < ApplicationController
  before_action :set_creditor, only: [:show, :edit, :update, :destroy]

  # GET /creditors
  # GET /creditors.json
  def index
    @creditors = Creditor.order(:id)
  end

  # GET /creditors/1
  # GET /creditors/1.json
  def show
  end

  # GET /creditors/new
  def new
    @creditor = Creditor.new
  end

  # GET /creditors/1/edit
  def edit
  end

  # POST /creditors
  # POST /creditors.json
  def create
    @creditor = Creditor.new(creditor_params)

    respond_to do |format|
      if @creditor.save
        format.html { redirect_to @creditor, notice: 'Creditor was successfully created.' }
        format.json { render :show, status: :created, location: @creditor }
      else
        format.html { render :new }
        format.json { render json: @creditor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creditors/1
  # PATCH/PUT /creditors/1.json
  def update
    respond_to do |format|
      if @creditor.update(creditor_params)
        format.html { redirect_to @creditor, notice: 'Creditor was successfully updated.' }
        format.json { render :show, status: :ok, location: @creditor }
      else
        format.html { render :edit }
        format.json { render json: @creditor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creditors/1
  # DELETE /creditors/1.json
  def destroy
    @creditor.destroy
    respond_to do |format|
      format.html { redirect_to creditors_url, notice: 'Creditor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creditor
      @creditor = Creditor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def creditor_params
      params.require(:creditor).permit(:name, :sum, :months, :rate, :period, :delay_rate, :created_at)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_creditor

  def create
    @creditor.payments.create! payments_params
    redirect_to @creditor
  end

  private
    def set_creditor
      @creditor = Creditor.find(params[:creditor_id])
    end

    def payments_params
      params.required(:payment).permit(:amount, :created_at)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
    if (sum = params['sum']) && sum!=''
      @expected_receipts = Creditor.receipts(sum.to_i, Creditor::DEFAULT_RATE)
      @historical_receipts = Creditor.receipts(sum.to_i, Creditor::rate_of_return)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creditors_helper.rb
module CreditorsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/creditors/_form.html.erb
<%= form_for @creditor, :html => { :class => "form-horizontal creditor" } do |f| %>

  <% if @creditor.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@creditor.errors.count, "error") %> prohibited this creditor from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @creditor.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :sum, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :sum, :class => 'form-control' %>
    </div>
    <%=f.error_span(:sum) %>
  </div>
  <div class="form-group">
    <%= f.label :months, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :months, :class => 'form-control' %>
    </div>
    <%=f.error_span(:months) %>
  </div>
  <div class="form-group">
    <%= f.label :rate, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :rate, :class => 'form-control' %>
    </div>
    <%=f.error_span(:rate) %>
  </div>
  <div class="form-group">
    <%= f.label :period, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :period, :class => 'form-control' %>
    </div>
    <%=f.error_span(:period) %>
  </div>
  <div class="form-group">
    <%= f.label :delay_rate, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :delay_rate, :class => 'form-control' %>
    </div>
    <%=f.error_span(:delay_rate) %>
  </div>
  <div class="form-group">
    <%= f.label :created_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_field :created_at, class: 'form-control', max: Date.today %>
    </div>
    <%=f.error_span(:created_at) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                creditors_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/creditors/edit.html.erb
<%- model_class = Creditor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/creditors/index.html.erb
<%- model_class = Creditor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:sum) %></th>
      <th><%= model_class.human_attribute_name(:months) %></th>
      <th><%= model_class.human_attribute_name(:rate) %></th>
      <th><%= model_class.human_attribute_name(:period) %></th>
      <th><%= model_class.human_attribute_name(:delay_rate) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:rate_of_return) %> %</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @creditors.each do |creditor| %>
      <tr>
        <td><%= link_to creditor.id, creditor_path(creditor) %></td>
        <td><%= creditor.name %></td>
        <td><%= creditor.sum %></td>
        <td><%= creditor.months %></td>
        <td><%= creditor.rate %></td>
        <td><%= creditor.period %></td>
        <td><%= creditor.delay_rate %></td>
        <td><%=l creditor.created_at %></td>
        <td><%= creditor.rate_of_return %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      creditor_path(creditor), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_creditor_path(creditor), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      creditor_path(creditor),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_creditor_path,
            :class => 'btn btn-primary' %>

app/views/creditors/new.html.erb
<%- model_class = Creditor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/creditors/show.html.erb
<%- model_class = Creditor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @creditor.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sum) %>:</strong></dt>
  <dd><%= @creditor.sum %></dd>
  <dt><strong><%= model_class.human_attribute_name(:months) %>:</strong></dt>
  <dd><%= @creditor.months %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rate) %>:</strong></dt>
  <dd><%= @creditor.rate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:period) %>:</strong></dt>
  <dd><%= @creditor.period %></dd>
  <dt><strong><%= model_class.human_attribute_name(:delay_rate) %>:</strong></dt>
  <dd><%= @creditor.delay_rate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:created_at) %>:</strong></dt>
  <dd><%= @creditor.created_at.to_s(:long) %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              creditors_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_creditor_path(@creditor), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              creditor_path(@creditor),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<br><br>

<h2>Payments</h2>
<div id="payments">
  <%= render @creditor.payments %>
</div>
<%= render 'payments/new', creditor: @creditor %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Credit" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <% if false %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <% end %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Credit</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'calculator', '/' %></li>
            <li><%= link_to 'creditors', creditors_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <br>
        <p>Powerand 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/payments/_new.html.erb
<%= form_for([ @creditor, Payment.new ], remote: true) do |form| %>
  <div class="field">
    <%= form.label :payment_amount %>
    <%= form.number_field :amount, id: :payment_amount %>
  </div>
  <div class="field">
    <%= form.label :payment_created_at %>
    <%= form.date_field :created_at, id: :payment_created_at %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<p><%= payment.amount %> -- <%= payment.created_at.to_s(:long) %></p>